# Generated by Django 3.0.2 on 2020-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200110_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number_phone',
            field=models.IntegerField(),
        ),
    ]
