# Generated by Django 3.0.2 on 2020-01-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200110_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer',
            field=models.BooleanField(default=True),
        ),
    ]
