# Generated by Django 3.0.2 on 2020-01-15 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200114_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_testimoni', models.CharField(max_length=11)),
                ('fullname', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('cover', models.ImageField(upload_to=users.models.Testimoni.path_upload)),
                ('cropping', image_cropping.fields.ImageRatioField('cover', '700x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
