# Generated by Django 3.0.2 on 2020-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_testimoni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimoni',
            name='id',
        ),
        migrations.AlterField(
            model_name='testimoni',
            name='id_testimoni',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
