# Generated by Django 3.0.2 on 2020-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200115_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
