# Generated by Django 3.0.2 on 2020-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='id',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='id_subscribe',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
