# Generated by Django 3.0.2 on 2020-01-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200114_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimoni',
        ),
    ]
