# Generated by Django 3.0.2 on 2020-01-17 14:48

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_blog', models.CharField(max_length=11)),
                ('cover', image_cropping.fields.ImageCropField(upload_to=blog.models.Blog.path_upload)),
                ('cropping', image_cropping.fields.ImageRatioField('cover', '1900x1267', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_show', models.BooleanField(default=False)),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('timeUpdate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
