# Generated by Django 3.0.2 on 2020-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200118_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
