# Generated by Django 3.0.2 on 2020-01-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_lodging_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
