# Generated by Django 3.0.2 on 2020-01-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_auto_20200120_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='cover',
        ),
    ]
