# Generated by Django 3.0.2 on 2020-01-20 01:49

import destination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0009_remove_destination_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='cover',
            field=models.ImageField(default='', upload_to=destination.models.Destination.path_upload1),
            preserve_default=False,
        ),
    ]
