# Generated by Django 3.0.2 on 2020-01-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0010_destination_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='croppingProfile',
        ),
    ]
