# Generated by Django 3.0.2 on 2020-01-20 01:55

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0013_destination_croppingcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='croppingCover',
            field=image_cropping.fields.ImageRatioField('cover', '1900x1267', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='croppingCover'),
        ),
    ]
