# Generated by Django 3.0.2 on 2020-01-20 01:59

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0014_auto_20200120_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='croppingCover',
            field=image_cropping.fields.ImageRatioField('cover', '1900x1267', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='croppingCover'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='croppingProfile',
            field=image_cropping.fields.ImageRatioField('profile', '700x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='croppingProfile'),
        ),
    ]
