# Generated by Django 3.0.2 on 2020-01-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0015_auto_20200120_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae cumque eius modi expedita accusamus alias error totam ab magnam a mollitia magni, distinctio temporibus optio illo sapiente, odio unde natus.'),
        ),
    ]
