# Generated by Django 3.0.2 on 2020-01-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0016_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination'),
        ),
    ]
