# Generated by Django 3.0.2 on 2020-01-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosmedteam',
            name='name',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('twitter', 'Twitter')], max_length=9),
        ),
    ]
